export const routes = {
  home: "/",
  about: "/about",
  helpDesk: "/help-desk",
  faqs:"/#faqs",
  exam: "/exam",
  contact: "/contact-us",
  codeOfEthic: "/code-of-ethics",
  privacy: "/privacy",
  terms: "/terms",
  explore: "/dashboard/learning-hub",
  wishList: "/dashboard/learning-hub/wish-list",
  myCourse: "/dashboard/learning-hub/my-course",
  tutor: "/dashboard/tutor",
  jobs: "/dashboard/job-seeker",
  messages: "/dashboard/messages",
};
